FROM alpine:3

LABEL author="Achmad Sidik Fauzi"
LABEL company="Fauzi Yarro" website="http://github.com/asidikfauzi/"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"